In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\amit\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\amit\appdata\roaming\python\python312\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\amit\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\amit\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\amit\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\amit\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [6]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
s = pd.Series([1,2,3,4], index=["A",'B', 'C','D'])
s

A    1
B    2
C    3
D    4
dtype: int64

In [ ]:
data_1 = [[1,111,'ahmed'],
          [2,222,'Dai'],
          [3,333,'Youssef'],
          [4,444,'abdalla']
         ]
# type(data_1)
# print(data_1)
x = ["index","ID","Name"]
df = pd.DataFrame(data_1,columns=["index","ID","Name"])
df.dtypes
df.dtypes

dtype('O')

In [16]:
data_2 = {'s1':[10,15,17,9],
          's2':[8,7,12,15],
          's3':['math','cs', 'stat','OR']}
df = pd.DataFrame(data_2)
df

   s1  s2    s3
0  10   8  math
1  15   7    cs
2  17  12  stat
3   9  15    OR

In [17]:
display(df)

   s1  s2    s3
0  10   8  math
1  15   7    cs
2  17  12  stat
3   9  15    OR

In [22]:
def abs():
    return f"hello"

In [35]:
class test:
    
    def __init__(self, name: str):
        self.name = name
    
    @property
    def info(self):
        """  
        this method get only info abut the name of std
        """
        
        return self. name

In [33]:
t1= test("George")
t1.info

'George'

In [78]:
data_1 = [[1,111,'ahmed'],
          [2,111,'Dai'],
          [3,333,'Youssef'],
          [4,444,'abdalla']
         ]
type(data_1)
# print(data_1)
df = pd.DataFrame(data_1,columns=["index","ID","Name"])
display(df)
# df.dtypes

   index   ID     Name
0      1  111    ahmed
1      2  111      Dai
2      3  333  Youssef
3      4  444  abdalla

In [79]:
df["Name"] = df ["Name"].astype("category")
df.dtypes

index       int64
ID          int64
Name     category
dtype: object

In [80]:
# EDA  Exploratory DATA ANALYSIS
df.head(2)

   index   ID   Name
0      1  111  ahmed
1      2  111    Dai

In [81]:
df.tail(1)

   index   ID     Name
3      4  444  abdalla

In [82]:
df.describe()

          index      ID
count  4.000000    4.00
mean   2.500000  249.75
std    1.290994  166.50
min    1.000000  111.00
25%    1.750000  111.00
50%    2.500000  222.00
75%    3.250000  360.75
max    4.000000  444.00

In [83]:
df.describe(include='category')

       Name
count     4
unique    4
top     Dai
freq      1

In [84]:
df['Name'].unique()

['ahmed', 'Dai', 'Youssef', 'abdalla']
Categories (4, object): ['Dai', 'Youssef', 'abdalla', 'ahmed']

In [85]:
df['ID'].max()

444

In [86]:
df['ID'].idxmax()

3

In [87]:
df['ID'].min()

111

In [88]:
df['ID'].idxmin()

0

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   4 non-null      int64
 1   ID      4 non-null      int64
 2   Name    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 404.0 bytes

In [90]:
d= df["ID"].value_counts()
d

ID
111    2
333    1
444    1
Name: count, dtype: int64

In [94]:
d= df["ID"]
d

0    111
1    111
2    333
3    444
Name: ID, dtype: int64

In [95]:
df['ID'].values

array([111, 111, 333, 444], dtype=int64)

In [96]:
df.values

array([[1, 111, 'ahmed'],
       [2, 111, 'Dai'],
       [3, 333, 'Youssef'],
       [4, 444, 'abdalla']], dtype=object)

In [97]:
df.replace(111, "george")

   index      ID     Name
0      1  george    ahmed
1      2  george      Dai
2      3     333  Youssef
3      4     444  abdalla

In [ ]:
df.replace({333:"youssef", 444:"Asmaa"})

   index       ID     Name
0      1      111    ahmed
1      2      111      Dai
2      3  youssef  Youssef
3      4    Asmaa  abdalla

In [104]:
def duplicate(x):
    return x*2
df['index'].apply(lambda x: x*2)

0    2
1    4
2    6
3    8
Name: index, dtype: int64

In [106]:
data_1 = [[1,111,'ahmed'],
          [2,111,'Dai'],
          [3,333,'Youssef'],
          [4,444,'abdalla']
         ]
type(data_1)
# print(data_1)
df = pd.DataFrame(data_1,columns=["index","ID","Name"])
display(df)
# df.dtypes

   index   ID     Name
0      1  111    ahmed
1      2  111      Dai
2      3  333  Youssef
3      4  444  abdalla

In [116]:
df.ID.iloc[0:2]

0    111
1    111
Name: ID, dtype: int64

In [127]:
X= df.iloc[:,0:2]
print(X)
y= df.iloc[:,-1]
print(y)

   index   ID
0      1  111
1      2  111
2      3  333
3      4  444
0      ahmed
1        Dai
2    Youssef
3    abdalla
Name: Name, dtype: object

In [132]:
data_1 = [[1,111,'ahmed'],
          [2,111,'Dai'],
          [3,333,'Youssef'],
          [4,444,'abdalla']
         ]
type(data_1)
# print(data_1)
df = pd.DataFrame(data_1,columns=["index","ID","Name"])
display(df)
df.dtypes

   index   ID     Name
0      1  111    ahmed
1      2  111      Dai
2      3  333  Youssef
3      4  444  abdalla

index     int64
ID        int64
Name     object
dtype: object

In [140]:
new_co  = df.index + df.ID
df.insert(3,"new_feature", new_co)
df

   index   ID     Name  new_feature
0      1  111    ahmed          111
1      2  111      Dai          112
2      3  333  Youssef          335
3      4  444  abdalla          447

In [ ]:
df.drop('new_feature', axis=1,inplace=False)
df

   index   ID     Name
0      1  111    ahmed
1      2  111      Dai
2      3  333  Youssef
3      4  444  abdalla

In [144]:
#to read table from linke or you can put the path of your own tabl
data=pd.read_table('http://bit.ly/movieusers')
data.head()

   1|24|M|technician|85711
0       2|53|F|other|94043
1      3|23|M|writer|32067
2  4|24|M|technician|43537
3       5|33|F|other|15213
4   6|42|M|executive|98101

In [ ]:
data=pd.read_table('http://bit.ly/movieusers', sep='|')
data.head()

   1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

In [146]:
data=pd.read_table('http://bit.ly/movieusers', sep='|', header= None)
data.head()

   0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [147]:
header_colums = ['index','age','gender','dept','postal_code']
data=pd.read_table('http://bit.ly/movieusers', sep='|', header= None, names = header_colums)
data.head()

   index  age gender        dept postal_code
0      1   24      M  technician       85711
1      2   53      F       other       94043
2      3   23      M      writer       32067
3      4   24      M  technician       43537
4      5   33      F       other       15213

In [148]:
user_info=pd.read_csv('http://bit.ly/uforeports')
user_info.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [150]:
user_info['Colors Reported'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Colors Reported, dtype: object

In [151]:
user_info.shape

(18241, 5)

In [153]:
user_info.City + ' ' + user_info.State

0                      Ithaca NY
1                 Willingboro NJ
2                     Holyoke CO
3                     Abilene KS
4        New York Worlds Fair NY
                  ...
18236              Grant Park IL
18237             Spirit Lake IA
18238             Eagle River WI
18239             Eagle River WI
18240                    Ybor FL
Length: 18241, dtype: object

In [154]:
user_info['location'] =  user_info.City + ' ' + user_info.State
user_info.head()

,City,Colors Reported,Shape Reported,State,Time,location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca NY
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro NJ
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke CO
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene KS
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair NY

In [156]:
user_info.to_csv('new_features.csv')

In [158]:
bew_file = pd.read_csv('new_features.csv')
bew_file.head()

,Unnamed: 0,City,Colors Reported,Shape Reported,State,Time,location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca NY
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro NJ
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke CO
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene KS
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair NY